[bot]
token = "TOKEN"

[database]
models = ["app.db.functions", "aerich.models"]

[storage]
use_persistent_storage = false

[settings]
owner_id = 123
throttling_rate = 0.5
use_webhook = false
use_pyrogram_client = false
drop_pending_updates = false

[math]
max_matrix = 8
max_vars = 7
max_modulo = 1000000000000000 # 1e15
max_elements = 101
factorise_max = 1000000000000 # 1e12
